### ISSUE TITLE
Add trusted_host_pattern to settings.php

### ISSUE THREAD

**Issue by jmonkfish** [wodby/drupal#1]
Without adding docker.drupal.locahost to the trusted_host_pattern, installing new modules will catch a 403 authorize.php error, and the installation will fail.

I added this to /web/sites/default/settings.php
```
 $settings['trusted_host_patterns'] = array(                                
   '^drupal\.docker\.localhost$',                                             
 ); 
```
And then installing modules works fine.

Even better would be to set the hostname as an ENV variable in docker-compose.yml, such as mysite.localhost.  Then a script can add that as a trusted_host_pattern in settings.php.  I don't really have experience with that, but sure does sound good!

**Comment by csandanov** [comment]
`.localhost`, `.local`, `.loc` added as default trusted hosts
