### ISSUE TITLE
Drupal root has been fixed

### ISSUE THREAD

**Issue by vothanhbinhlt** [wodby/drupal#12]
Hello wodby team. Look this file https://github.com/wodby/drupal/blob/master/8/bin/init. Now you have fixed DRUPAL_DOC = "/var/www/html/web". I could not change the DRUPAL_DOC to /var/www/html.

**Comment by vothanhbinhlt** [comment]
I think you should change `${APP_ROOT}/web` to `${DRUPAL_ROOT}` in this file

**Comment by csandanov** [comment]
Not sure what's the issue here, do you want to use a different directory inside `$APP_ROOT`? In this case, we should perhaps use `$DOCROOT_SUBDIR` that we define in the dockerfile. Please note you can always use `wodby/drupal-php` and install Drupal however you like.

**Comment by vothanhbinhlt** [comment]
Thanks @csandanov. I change to use `wodby/drupal-php`, and it worked. Thank you so much
