### ISSUE TITLE
Set the drupal tag to 8 but Drupal 9 installed

### ISSUE THREAD

**Issue by hsb1007** [wodby/drupal#14]
I am struggling to install the drupal version 8 for some of the module  compatibility but the actual drupal version installed from the process is still 9.

How do we manage to downgrade?

![image](https://user-images.githubusercontent.com/4149765/102740896-f50e8880-43a4-11eb-8e87-2d89f797f22b.png)

![image](https://user-images.githubusercontent.com/4149765/102740841-d60ff680-43a4-11eb-9c7a-60c8917bcdeb.png)

**Comment by csandanov** [comment]
not sure how I missed that, I've checked `wodby/drupal:8` and it contains correct drupal version
