### ISSUE TITLE
Upgrade Drupal to drush 9.x for Drupal 8.4.x support

### ISSUE THREAD

**Issue by ravindrasingh22** [wodby/drupal#3]
Drush 8.x doesn't support Drupal 8.4.x, and it is clearly mentioned on http://docs.drush.org/en/master/install/ page. Please upgrade the wodby/drupal

**Comment by csandanov** [comment]
we use drupal-composer for the vanilla and it seems [drush 8 supports 8.4](https://github.com/drupal-composer/drupal-project/pull/304#issuecomment-335830593) after all. Did you have any issues with drush 8.x?

**Comment by esteinborn** [comment]
Drush 8.1.12+ supports Drupal 8.4.x. Recommend closing this issue.

Details:
https://www.drupal.org/node/2874827
