### ISSUE TITLE
Can't have a host name except for  .localhost, .local, .loc

### ISSUE THREAD

**Issue by mattferderer** [wodby/drupal#4]
Due to the fix for https://github.com/wodby/drupal/issues/1 it will not allow a user to change the hostname to something that isn't .localhost, .local, .loc.  You will get a `The provided host name is not valid for this server.` error.

As suggested in that issue, you could use `getenv` to get one that could be provided from docker-compose.yml & could be set to a default of `.localhost`.  Otherwise, at least providing better info in the docs could help this. 

I ran into this because the version of Windows I'm using isn't a fan of me pointing a .localhost domain to a different IP.

**Comment by csandanov** [comment]
Since `wodby/drupa:x-3.3.2` it's now possible to override default patterns via environment variable `DRUPAL_TRUSTED_HOST_PATTERNS`
